<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class ManPower extends Model
{
    protected $table="manpower_requests";
    protected $primaryKey="SNO";
    protected $fillable = 
    [
        'SNO',
        'CASEID',
        'CHILD_CASEID',
        'RAISER',
        'MANPOWER_DESG',
        'PLANT',
        'R_DT',
        'REQ_FOR',
        'REQ_MAIL',
        'DEPT',
        'NUM_REQUIRE',
        'POSITION',
        'REQUIRE_BY_DATE',
        'EDUCATION',
        'TECH_SKILLS',
        'SOFT_SKILLS',
        'EXP',
        'RECRUIT_FOR',
        'RECRUIT_CYCLE',
        'REPORTING',
        'REPLACEMENT_NAME',
        'JOB_DESC',
        'STATUS',
        'STATUS_DT',
        'REMARKS',
        'EMPID',
        'EVC_DT',
        'PRJ_HEAD_MAIL',
        'FUNC_HEAD_MAIL',
        'GM_NAME',
        'GM_STATUS',
        'RAISER_DATE',
        'GM_DATE',
        'PRJ_DATE',
        'FUNC_DATE',
        'SP_DATE',
        'EVC_DATE',
        'PRJ_NAME',
        'PRJ_STATUS',
        'FUNC_STATUS',
        'SP_STATUS',
        'EVC_STATUS',
        'FUNC_NAME',
        'SP_NAME',
        'EVC_NAME',
        'CUR_USR',
        'CUR_STATUS',
        'CUR_TASK',
        'CASE_SERIAL',
        'JOB_TIT',
        'REQ_BY_DT',
        'GM_REM',
        'PRJ_REM',
        'FUNC_REM',
        'SP_REM',
        'EVC_REM',
        'REV1_COMM',
        'REV2_COMM',
        'HR',
        'HO_HOD_NAME',
        'HO_HOD_DATE',
        'HO_HOD_STATUS',
        'HO_HOD_REM',
        'DEL',
        'LST_UPDT_DT',
        "Wip_Date"  ,
        "updated_date",  
        "Joining_Date" ,
        "Reverted_Date",
        "Transfer_Date",
    ];
public $timestamps=false;    

}
